export interface TataEV {
  id: string;
  name: string;
  batteryCapacity: number; // kWh
  range: number; // km (ARAI certified)
  efficiency: number; // km per kWh
  fastChargeRate: number; // kW max DC
  slowChargeRate: number; // kW AC
  image: string;
}

export const tataEVs: TataEV[] = [
  {
    id: 'nexon-ev-max',
    name: 'Tata Nexon EV Max',
    batteryCapacity: 40.5,
    range: 437,
    efficiency: 10.8,
    fastChargeRate: 50,
    slowChargeRate: 7.2,
    image: '/nexon-ev.png'
  },
  {
    id: 'nexon-ev',
    name: 'Tata Nexon EV',
    batteryCapacity: 30.2,
    range: 312,
    efficiency: 10.3,
    fastChargeRate: 50,
    slowChargeRate: 7.2,
    image: '/nexon-ev.png'
  },
  {
    id: 'tiago-ev',
    name: 'Tata Tiago EV',
    batteryCapacity: 24,
    range: 315,
    efficiency: 13.1,
    fastChargeRate: 50,
    slowChargeRate: 7.2,
    image: '/tiago-ev.png'
  },
  {
    id: 'tigor-ev',
    name: 'Tata Tigor EV',
    batteryCapacity: 26,
    range: 315,
    efficiency: 12.1,
    fastChargeRate: 25,
    slowChargeRate: 7.2,
    image: '/tigor-ev.png'
  },
  {
    id: 'punch-ev',
    name: 'Tata Punch EV',
    batteryCapacity: 35,
    range: 421,
    efficiency: 12,
    fastChargeRate: 50,
    slowChargeRate: 7.2,
    image: '/punch-ev.png'
  }
];

export interface ChargingStation {
  id: string;
  name: string;
  operator: string;
  lat: number;
  lng: number;
  chargerTypes: ('DC Fast' | 'AC Slow' | 'CCS2' | 'CHAdeMO')[];
  maxPower: number; // kW
  available: number;
  total: number;
  pricePerKwh: number; // INR
  rating: number;
  amenities: string[];
  status: 'available' | 'busy' | 'offline';
}

export const mockChargingStations: ChargingStation[] = [
  {
    id: 'cs1',
    name: 'Tata Power EZ Charge - Mathura',
    operator: 'Tata Power',
    lat: 27.4924,
    lng: 77.6737,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 18,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs2',
    name: 'EESL Charging Hub - Agra',
    operator: 'EESL',
    lat: 27.1767,
    lng: 78.0081,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 30,
    available: 1,
    total: 2,
    pricePerKwh: 15,
    rating: 4.0,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs3',
    name: 'Fortum Charge - Gwalior',
    operator: 'Fortum',
    lat: 26.2183,
    lng: 78.1828,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 20,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Lounge'],
    status: 'available'
  },
  {
    id: 'cs4',
    name: 'ChargeZone - Jhansi',
    operator: 'ChargeZone',
    lat: 25.4484,
    lng: 78.5685,
    chargerTypes: ['DC Fast'],
    maxPower: 50,
    available: 0,
    total: 2,
    pricePerKwh: 16,
    rating: 3.8,
    amenities: ['Restroom'],
    status: 'busy'
  },
  {
    id: 'cs5',
    name: 'Tata Power - Bhopal Highway',
    operator: 'Tata Power',
    lat: 23.2599,
    lng: 77.4126,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 18,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs6',
    name: 'Tata Power - Connaught Place Delhi',
    operator: 'Tata Power',
    lat: 28.6315,
    lng: 77.2167,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 4,
    total: 6,
    pricePerKwh: 19,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Mall'],
    status: 'available'
  },
  {
    id: 'cs7',
    name: 'EESL - Noida Sector 62',
    operator: 'EESL',
    lat: 28.6273,
    lng: 77.3714,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 16,
    rating: 4.2,
    amenities: ['Restroom', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs8',
    name: 'ChargeZone - Gurugram Cyber Hub',
    operator: 'ChargeZone',
    lat: 28.4595,
    lng: 77.0266,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 3,
    total: 5,
    pricePerKwh: 20,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Lounge', 'Mall'],
    status: 'available'
  },
  {
    id: 'cs9',
    name: 'Tata Power - Mumbai BKC',
    operator: 'Tata Power',
    lat: 19.0654,
    lng: 72.8696,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 5,
    total: 8,
    pricePerKwh: 21,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Lounge'],
    status: 'available'
  },
  {
    id: 'cs10',
    name: 'Fortum - Pune Hinjewadi',
    operator: 'Fortum',
    lat: 18.5912,
    lng: 73.7380,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 18,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs11',
    name: 'EESL - Bangalore Electronic City',
    operator: 'EESL',
    lat: 12.8456,
    lng: 77.6603,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 6,
    pricePerKwh: 17,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs12',
    name: 'Tata Power - Bangalore Whitefield',
    operator: 'Tata Power',
    lat: 12.9698,
    lng: 77.7500,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 4,
    total: 6,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Mall'],
    status: 'available'
  },
  {
    id: 'cs13',
    name: 'ChargeZone - Chennai OMR',
    operator: 'ChargeZone',
    lat: 12.9516,
    lng: 80.2421,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 18,
    rating: 4.2,
    amenities: ['Restroom', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs14',
    name: 'Tata Power - Hyderabad HITEC City',
    operator: 'Tata Power',
    lat: 17.4435,
    lng: 78.3772,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 5,
    total: 8,
    pricePerKwh: 18,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Mall'],
    status: 'available'
  },
  {
    id: 'cs15',
    name: 'EESL - Kolkata Salt Lake',
    operator: 'EESL',
    lat: 22.5800,
    lng: 88.4179,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 15,
    rating: 4.1,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs16',
    name: 'Fortum - Ahmedabad SG Highway',
    operator: 'Fortum',
    lat: 23.0469,
    lng: 72.5169,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 3,
    total: 5,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs17',
    name: 'Tata Power - Jaipur MI Road',
    operator: 'Tata Power',
    lat: 26.9157,
    lng: 75.7997,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 17,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs18',
    name: 'ChargeZone - Lucknow Gomti Nagar',
    operator: 'ChargeZone',
    lat: 26.8570,
    lng: 81.0139,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 1,
    total: 3,
    pricePerKwh: 16,
    rating: 4.0,
    amenities: ['Restroom', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs19',
    name: 'EESL - Chandigarh Sector 17',
    operator: 'EESL',
    lat: 30.7415,
    lng: 76.7836,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 4,
    pricePerKwh: 15,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs20',
    name: 'Tata Power - Udaipur City Palace',
    operator: 'Tata Power',
    lat: 24.5764,
    lng: 73.6833,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 18,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs21',
    name: 'Fortum - Goa Panjim',
    operator: 'Fortum',
    lat: 15.4989,
    lng: 73.8278,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 20,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Beach Access'],
    status: 'available'
  },
  {
    id: 'cs22',
    name: 'ChargeZone - Surat Ring Road',
    operator: 'ChargeZone',
    lat: 21.1702,
    lng: 72.8311,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 4,
    total: 6,
    pricePerKwh: 17,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs23',
    name: 'Tata Power - Vadodara Alkapuri',
    operator: 'Tata Power',
    lat: 22.3072,
    lng: 73.1812,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 18,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs24',
    name: 'EESL - Indore Vijay Nagar',
    operator: 'EESL',
    lat: 22.7533,
    lng: 75.8937,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.1,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs25',
    name: 'Fortum - Nagpur Dharampeth',
    operator: 'Fortum',
    lat: 21.1458,
    lng: 79.0882,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 5,
    pricePerKwh: 19,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs26',
    name: 'Tata Power - Nashik Mumbai Highway',
    operator: 'Tata Power',
    lat: 19.9975,
    lng: 73.7898,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 18,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs27',
    name: 'ChargeZone - Coimbatore RS Puram',
    operator: 'ChargeZone',
    lat: 11.0168,
    lng: 76.9558,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 17,
    rating: 4.2,
    amenities: ['Restroom', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs28',
    name: 'EESL - Kochi Marine Drive',
    operator: 'EESL',
    lat: 9.9816,
    lng: 76.2757,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 4,
    pricePerKwh: 16,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs29',
    name: 'Tata Power - Mysore Palace Road',
    operator: 'Tata Power',
    lat: 12.3051,
    lng: 76.6551,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 17,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs30',
    name: 'Fortum - Vizag Beach Road',
    operator: 'Fortum',
    lat: 17.7231,
    lng: 83.3013,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 18,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Beach View'],
    status: 'available'
  },
  {
    id: 'cs31',
    name: 'ChargeZone - Bhubaneswar Patia',
    operator: 'ChargeZone',
    lat: 20.3555,
    lng: 85.8245,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 16,
    rating: 4.1,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs32',
    name: 'Tata Power - Patna Kankarbagh',
    operator: 'Tata Power',
    lat: 25.5941,
    lng: 85.1376,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 3.9,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs33',
    name: 'EESL - Ranchi Main Road',
    operator: 'EESL',
    lat: 23.3441,
    lng: 85.3096,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.0,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs34',
    name: 'Fortum - Dehradun Rajpur Road',
    operator: 'Fortum',
    lat: 30.3165,
    lng: 78.0322,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs35',
    name: 'Tata Power - Amritsar Golden Temple',
    operator: 'Tata Power',
    lat: 31.6200,
    lng: 74.8765,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 4,
    pricePerKwh: 17,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs36',
    name: 'ChargeZone - Jammu Gandhi Nagar',
    operator: 'ChargeZone',
    lat: 32.7266,
    lng: 74.8570,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 1,
    total: 2,
    pricePerKwh: 18,
    rating: 4.0,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs37',
    name: 'EESL - Shimla Mall Road',
    operator: 'EESL',
    lat: 31.1048,
    lng: 77.1734,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 30,
    available: 1,
    total: 2,
    pricePerKwh: 16,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs38',
    name: 'Tata Power - Manali Highway',
    operator: 'Tata Power',
    lat: 32.2396,
    lng: 77.1887,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 2,
    pricePerKwh: 20,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'Mountain View'],
    status: 'available'
  },
  {
    id: 'cs39',
    name: 'Fortum - Guwahati GS Road',
    operator: 'Fortum',
    lat: 26.1445,
    lng: 91.7362,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 18,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs40',
    name: 'ChargeZone - Siliguri Sevoke Road',
    operator: 'ChargeZone',
    lat: 26.7271,
    lng: 88.3953,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 17,
    rating: 4.1,
    amenities: ['Restroom', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs41',
    name: 'Tata Power - Raipur VIP Road',
    operator: 'Tata Power',
    lat: 21.2514,
    lng: 81.6296,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 17,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs42',
    name: 'EESL - Thiruvananthapuram MG Road',
    operator: 'EESL',
    lat: 8.5241,
    lng: 76.9366,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 16,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs43',
    name: 'Fortum - Mangalore Forum Mall',
    operator: 'Fortum',
    lat: 12.9141,
    lng: 74.8560,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Mall'],
    status: 'available'
  },
  {
    id: 'cs44',
    name: 'Tata Power - Mumbai-Pune Expressway',
    operator: 'Tata Power',
    lat: 18.7557,
    lng: 73.4091,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 120,
    available: 6,
    total: 10,
    pricePerKwh: 22,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi', 'Lounge', 'Food Court'],
    status: 'available'
  },
  {
    id: 'cs45',
    name: 'ChargeZone - Delhi-Jaipur Highway',
    operator: 'ChargeZone',
    lat: 27.5530,
    lng: 76.6346,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 4,
    total: 6,
    pricePerKwh: 18,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs46',
    name: 'Tata Power - Gurugram IFFCO Chowk',
    operator: 'Tata Power',
    lat: 28.4650,
    lng: 77.0527,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 3,
    total: 5,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs47',
    name: 'EESL - Neemrana Logistics Hub',
    operator: 'EESL',
    lat: 27.9914,
    lng: 76.3840,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 4,
    pricePerKwh: 15,
    rating: 4.1,
    amenities: ['Restroom'],
    status: 'available'
  },
  {
    id: 'cs48',
    name: 'Fortum - Ajmer Highway Stop',
    operator: 'Fortum',
    lat: 26.4499,
    lng: 74.6399,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 19,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs49',
    name: 'ChargeZone - Vadodara Highway North',
    operator: 'ChargeZone',
    lat: 22.4765,
    lng: 73.1150,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 5,
    pricePerKwh: 17,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe'],
    status: 'available'
  },
  {
    id: 'cs50',
    name: 'Tata Power - Surat Expressway',
    operator: 'Tata Power',
    lat: 21.1950,
    lng: 72.9000,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 60,
    available: 4,
    total: 6,
    pricePerKwh: 18,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  }
,
  {
    id: 'cs51',
    name: 'Tata Power - Delhi Sector 1',
    operator: 'Tata Power',
    lat: 28.5689,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 15,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs52',
    name: 'EESL - Mumbai Sector 2',
    operator: 'EESL',
    lat: 19.0460,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 16,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs53',
    name: 'Fortum - Bangalore Sector 3',
    operator: 'Fortum',
    lat: 12.9566,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 3,
    total: 5,
    pricePerKwh: 17,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs54',
    name: 'ChargeZone - Chennai Sector 4',
    operator: 'ChargeZone',
    lat: 13.0827,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 6,
    total: 6,
    pricePerKwh: 18,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs55',
    name: 'Tata Power - Kolkata Sector 5',
    operator: 'Tata Power',
    lat: 22.5876,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 19,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs56',
    name: 'EESL - Hyderabad Sector 6',
    operator: 'EESL',
    lat: 17.4150,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 2,
    total: 4,
    pricePerKwh: 20,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs57',
    name: 'Fortum - Pune Sector 7',
    operator: 'Fortum',
    lat: 18.5654,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 5,
    total: 5,
    pricePerKwh: 21,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs58',
    name: 'ChargeZone - Ahmedabad Sector 8',
    operator: 'ChargeZone',
    lat: 22.9775,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 5,
    total: 6,
    pricePerKwh: 22,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs59',
    name: 'Tata Power - Jaipur Sector 9',
    operator: 'Tata Power',
    lat: 26.8824,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 1,
    total: 3,
    pricePerKwh: 15,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs60',
    name: 'EESL - Lucknow Sector 1',
    operator: 'EESL',
    lat: 26.8317,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs61',
    name: 'Fortum - Delhi Sector 2',
    operator: 'Fortum',
    lat: 28.6139,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 4,
    total: 5,
    pricePerKwh: 17,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs62',
    name: 'ChargeZone - Mumbai Sector 3',
    operator: 'ChargeZone',
    lat: 19.0910,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 4,
    total: 6,
    pricePerKwh: 18,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs63',
    name: 'Tata Power - Bangalore Sector 4',
    operator: 'Tata Power',
    lat: 13.0016,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 19,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs64',
    name: 'EESL - Chennai Sector 5',
    operator: 'EESL',
    lat: 13.1277,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 20,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs65',
    name: 'Fortum - Kolkata Sector 6',
    operator: 'Fortum',
    lat: 22.5276,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 3,
    total: 5,
    pricePerKwh: 21,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs66',
    name: 'ChargeZone - Hyderabad Sector 7',
    operator: 'ChargeZone',
    lat: 17.3550,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 6,
    total: 6,
    pricePerKwh: 22,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs67',
    name: 'Tata Power - Pune Sector 8',
    operator: 'Tata Power',
    lat: 18.5054,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs68',
    name: 'EESL - Ahmedabad Sector 9',
    operator: 'EESL',
    lat: 23.0225,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 2,
    total: 4,
    pricePerKwh: 16,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs69',
    name: 'Fortum - Jaipur Sector 1',
    operator: 'Fortum',
    lat: 26.9274,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 5,
    total: 5,
    pricePerKwh: 17,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs70',
    name: 'ChargeZone - Lucknow Sector 2',
    operator: 'ChargeZone',
    lat: 26.8767,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 5,
    total: 6,
    pricePerKwh: 18,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs71',
    name: 'Tata Power - Delhi Sector 3',
    operator: 'Tata Power',
    lat: 28.6589,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 1,
    total: 3,
    pricePerKwh: 19,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs72',
    name: 'EESL - Mumbai Sector 4',
    operator: 'EESL',
    lat: 19.0310,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 4,
    total: 4,
    pricePerKwh: 20,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs73',
    name: 'Fortum - Bangalore Sector 5',
    operator: 'Fortum',
    lat: 12.9416,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 4,
    total: 5,
    pricePerKwh: 21,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs74',
    name: 'ChargeZone - Chennai Sector 6',
    operator: 'ChargeZone',
    lat: 13.0677,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 4,
    total: 6,
    pricePerKwh: 22,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs75',
    name: 'Tata Power - Kolkata Sector 7',
    operator: 'Tata Power',
    lat: 22.5726,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 15,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs76',
    name: 'EESL - Hyderabad Sector 8',
    operator: 'EESL',
    lat: 17.4000,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 16,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs77',
    name: 'Fortum - Pune Sector 9',
    operator: 'Fortum',
    lat: 18.5504,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 3,
    total: 5,
    pricePerKwh: 17,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs78',
    name: 'ChargeZone - Ahmedabad Sector 1',
    operator: 'ChargeZone',
    lat: 23.0675,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 6,
    total: 6,
    pricePerKwh: 18,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs79',
    name: 'Tata Power - Jaipur Sector 2',
    operator: 'Tata Power',
    lat: 26.8674,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 19,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs80',
    name: 'EESL - Lucknow Sector 3',
    operator: 'EESL',
    lat: 26.8167,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 2,
    total: 4,
    pricePerKwh: 20,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs81',
    name: 'Fortum - Delhi Sector 4',
    operator: 'Fortum',
    lat: 28.5989,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 5,
    total: 5,
    pricePerKwh: 21,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs82',
    name: 'ChargeZone - Mumbai Sector 5',
    operator: 'ChargeZone',
    lat: 19.0760,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 5,
    total: 6,
    pricePerKwh: 22,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs83',
    name: 'Tata Power - Bangalore Sector 6',
    operator: 'Tata Power',
    lat: 12.9866,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 1,
    total: 3,
    pricePerKwh: 15,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs84',
    name: 'EESL - Chennai Sector 7',
    operator: 'EESL',
    lat: 13.1127,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs85',
    name: 'Fortum - Kolkata Sector 8',
    operator: 'Fortum',
    lat: 22.6176,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 4,
    total: 5,
    pricePerKwh: 17,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs86',
    name: 'ChargeZone - Hyderabad Sector 9',
    operator: 'ChargeZone',
    lat: 17.3400,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 4,
    total: 6,
    pricePerKwh: 18,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs87',
    name: 'Tata Power - Pune Sector 1',
    operator: 'Tata Power',
    lat: 18.4904,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 19,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs88',
    name: 'EESL - Ahmedabad Sector 2',
    operator: 'EESL',
    lat: 23.0075,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 20,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs89',
    name: 'Fortum - Jaipur Sector 3',
    operator: 'Fortum',
    lat: 26.9124,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 3,
    total: 5,
    pricePerKwh: 21,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs90',
    name: 'ChargeZone - Lucknow Sector 4',
    operator: 'ChargeZone',
    lat: 26.8617,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 6,
    total: 6,
    pricePerKwh: 22,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs91',
    name: 'Tata Power - Delhi Sector 5',
    operator: 'Tata Power',
    lat: 28.6439,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs92',
    name: 'EESL - Mumbai Sector 6',
    operator: 'EESL',
    lat: 19.1210,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 2,
    total: 4,
    pricePerKwh: 16,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs93',
    name: 'Fortum - Bangalore Sector 7',
    operator: 'Fortum',
    lat: 12.9266,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 5,
    total: 5,
    pricePerKwh: 17,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs94',
    name: 'ChargeZone - Chennai Sector 8',
    operator: 'ChargeZone',
    lat: 13.0527,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 5,
    total: 6,
    pricePerKwh: 18,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs95',
    name: 'Tata Power - Kolkata Sector 9',
    operator: 'Tata Power',
    lat: 22.5576,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 1,
    total: 3,
    pricePerKwh: 19,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs96',
    name: 'EESL - Hyderabad Sector 1',
    operator: 'EESL',
    lat: 17.3850,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 4,
    total: 4,
    pricePerKwh: 20,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs97',
    name: 'Fortum - Pune Sector 2',
    operator: 'Fortum',
    lat: 18.5354,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 4,
    total: 5,
    pricePerKwh: 21,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs98',
    name: 'ChargeZone - Ahmedabad Sector 3',
    operator: 'ChargeZone',
    lat: 23.0525,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 4,
    total: 6,
    pricePerKwh: 22,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs99',
    name: 'Tata Power - Jaipur Sector 4',
    operator: 'Tata Power',
    lat: 26.9574,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 15,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs100',
    name: 'EESL - Lucknow Sector 5',
    operator: 'EESL',
    lat: 26.8017,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 16,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs101',
    name: 'Fortum - Delhi Sector 6',
    operator: 'Fortum',
    lat: 28.5839,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 3,
    total: 5,
    pricePerKwh: 17,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs102',
    name: 'ChargeZone - Mumbai Sector 7',
    operator: 'ChargeZone',
    lat: 19.0610,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 6,
    total: 6,
    pricePerKwh: 18,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs103',
    name: 'Tata Power - Bangalore Sector 8',
    operator: 'Tata Power',
    lat: 12.9716,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 19,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs104',
    name: 'EESL - Chennai Sector 9',
    operator: 'EESL',
    lat: 13.0977,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 2,
    total: 4,
    pricePerKwh: 20,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs105',
    name: 'Fortum - Kolkata Sector 1',
    operator: 'Fortum',
    lat: 22.6026,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 5,
    total: 5,
    pricePerKwh: 21,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs106',
    name: 'ChargeZone - Hyderabad Sector 2',
    operator: 'ChargeZone',
    lat: 17.4300,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 5,
    total: 6,
    pricePerKwh: 22,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs107',
    name: 'Tata Power - Pune Sector 3',
    operator: 'Tata Power',
    lat: 18.4754,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 1,
    total: 3,
    pricePerKwh: 15,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs108',
    name: 'EESL - Ahmedabad Sector 4',
    operator: 'EESL',
    lat: 22.9925,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs109',
    name: 'Fortum - Jaipur Sector 5',
    operator: 'Fortum',
    lat: 26.8974,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 4,
    total: 5,
    pricePerKwh: 17,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs110',
    name: 'ChargeZone - Lucknow Sector 6',
    operator: 'ChargeZone',
    lat: 26.8467,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 4,
    total: 6,
    pricePerKwh: 18,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs111',
    name: 'Tata Power - Delhi Sector 7',
    operator: 'Tata Power',
    lat: 28.6289,
    lng: 77.1690,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 19,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs112',
    name: 'EESL - Mumbai Sector 8',
    operator: 'EESL',
    lat: 19.1060,
    lng: 72.8577,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 20,
    rating: 4.7,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs113',
    name: 'Fortum - Bangalore Sector 9',
    operator: 'Fortum',
    lat: 13.0166,
    lng: 77.5946,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 3,
    total: 5,
    pricePerKwh: 21,
    rating: 4.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs114',
    name: 'ChargeZone - Chennai Sector 1',
    operator: 'ChargeZone',
    lat: 13.0377,
    lng: 80.2907,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 6,
    total: 6,
    pricePerKwh: 22,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs115',
    name: 'Tata Power - Kolkata Sector 2',
    operator: 'Tata Power',
    lat: 22.5426,
    lng: 88.4039,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs116',
    name: 'EESL - Hyderabad Sector 3',
    operator: 'EESL',
    lat: 17.3700,
    lng: 78.4467,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 2,
    total: 4,
    pricePerKwh: 16,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs117',
    name: 'Fortum - Pune Sector 4',
    operator: 'Fortum',
    lat: 18.5204,
    lng: 73.8367,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 5,
    total: 5,
    pricePerKwh: 17,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs118',
    name: 'ChargeZone - Ahmedabad Sector 5',
    operator: 'ChargeZone',
    lat: 23.0375,
    lng: 72.5714,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 60,
    available: 5,
    total: 6,
    pricePerKwh: 18,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs119',
    name: 'Tata Power - Jaipur Sector 6',
    operator: 'Tata Power',
    lat: 26.9424,
    lng: 75.8073,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 70,
    available: 1,
    total: 3,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs120',
    name: 'EESL - Lucknow Sector 7',
    operator: 'EESL',
    lat: 26.8917,
    lng: 80.9862,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 50,
    available: 4,
    total: 4,
    pricePerKwh: 20,
    rating: 4.6,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  }
,
  {
    id: 'cs121',
    name: 'Tata Power - Coorg Junction 1',
    operator: 'Tata Power',
    lat: 12.3760,
    lng: 75.6782,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs122',
    name: 'EESL - Mysuru Junction 2',
    operator: 'EESL',
    lat: 12.2658,
    lng: 76.5994,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs123',
    name: 'Fortum - Madurai Junction 3',
    operator: 'Fortum',
    lat: 9.9152,
    lng: 78.0998,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs124',
    name: 'ChargeZone - Trichy Junction 4',
    operator: 'ChargeZone',
    lat: 10.8005,
    lng: 78.7047,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs125',
    name: 'Tata Power - Salem Junction 5',
    operator: 'Tata Power',
    lat: 11.6943,
    lng: 78.1660,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs126',
    name: 'EESL - Tirunelveli Junction 6',
    operator: 'EESL',
    lat: 8.7639,
    lng: 77.7967,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs127',
    name: 'Fortum - Vijayawada Junction 7',
    operator: 'Fortum',
    lat: 16.4562,
    lng: 80.7080,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs128',
    name: 'ChargeZone - Visakhapatnam Junction 8',
    operator: 'ChargeZone',
    lat: 17.6568,
    lng: 83.1585,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs129',
    name: 'Tata Power - Warangal Junction 1',
    operator: 'Tata Power',
    lat: 17.9589,
    lng: 79.5541,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs130',
    name: 'EESL - Nashik Junction 2',
    operator: 'EESL',
    lat: 20.0075,
    lng: 73.7698,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs131',
    name: 'Fortum - Aurangabad Junction 3',
    operator: 'Fortum',
    lat: 19.9062,
    lng: 75.3433,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs132',
    name: 'ChargeZone - Solapur Junction 4',
    operator: 'ChargeZone',
    lat: 17.7099,
    lng: 75.9264,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs133',
    name: 'Tata Power - Nagpur Junction 5',
    operator: 'Tata Power',
    lat: 21.0958,
    lng: 79.1282,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs134',
    name: 'EESL - Indore Junction 6',
    operator: 'EESL',
    lat: 22.6896,
    lng: 75.9177,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs135',
    name: 'Fortum - Jabalpur Junction 7',
    operator: 'Fortum',
    lat: 23.1715,
    lng: 79.9264,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs136',
    name: 'ChargeZone - Gwalior Junction 8',
    operator: 'ChargeZone',
    lat: 26.2283,
    lng: 78.1428,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs137',
    name: 'Tata Power - Kota Junction 1',
    operator: 'Tata Power',
    lat: 25.2438,
    lng: 75.8448,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs138',
    name: 'EESL - Ajmer Junction 2',
    operator: 'EESL',
    lat: 26.4999,
    lng: 74.6399,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs139',
    name: 'Fortum - Jodhpur Junction 3',
    operator: 'Fortum',
    lat: 26.1889,
    lng: 73.0443,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs140',
    name: 'ChargeZone - Udaipur Junction 4',
    operator: 'ChargeZone',
    lat: 24.5554,
    lng: 73.7525,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs141',
    name: 'Tata Power - Bikaner Junction 5',
    operator: 'Tata Power',
    lat: 28.0129,
    lng: 73.3719,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs142',
    name: 'EESL - Bhubaneswar Junction 6',
    operator: 'EESL',
    lat: 20.3061,
    lng: 85.7645,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs143',
    name: 'Fortum - Cuttack Junction 7',
    operator: 'Fortum',
    lat: 20.4925,
    lng: 85.8430,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs144',
    name: 'ChargeZone - Ranchi Junction 8',
    operator: 'ChargeZone',
    lat: 23.3941,
    lng: 85.2896,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs145',
    name: 'Tata Power - Jamshedpur Junction 1',
    operator: 'Tata Power',
    lat: 22.7546,
    lng: 86.2029,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs146',
    name: 'EESL - Patna Junction 2',
    operator: 'EESL',
    lat: 25.5641,
    lng: 85.1576,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs147',
    name: 'Fortum - Siliguri Junction 3',
    operator: 'Fortum',
    lat: 26.7171,
    lng: 88.4353,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs148',
    name: 'ChargeZone - Guwahati Junction 4',
    operator: 'ChargeZone',
    lat: 26.1545,
    lng: 91.7962,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs149',
    name: 'Tata Power - Shillong Junction 5',
    operator: 'Tata Power',
    lat: 25.6088,
    lng: 91.8333,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs150',
    name: 'EESL - Imphal Junction 6',
    operator: 'EESL',
    lat: 24.8670,
    lng: 93.8968,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs151',
    name: 'Fortum - Agartala Junction 7',
    operator: 'Fortum',
    lat: 23.7815,
    lng: 91.2668,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs152',
    name: 'ChargeZone - Dehradun Junction 8',
    operator: 'ChargeZone',
    lat: 30.2865,
    lng: 78.0322,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs153',
    name: 'Tata Power - Haridwar Junction 1',
    operator: 'Tata Power',
    lat: 29.9357,
    lng: 78.1842,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs154',
    name: 'EESL - Shimla Junction 2',
    operator: 'EESL',
    lat: 31.1148,
    lng: 77.2134,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs155',
    name: 'Fortum - Manali Junction 3',
    operator: 'Fortum',
    lat: 32.2696,
    lng: 77.2487,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs156',
    name: 'ChargeZone - Jammu Junction 4',
    operator: 'ChargeZone',
    lat: 32.7766,
    lng: 74.7970,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs157',
    name: 'Tata Power - Amritsar Junction 5',
    operator: 'Tata Power',
    lat: 31.5840,
    lng: 74.8323,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs158',
    name: 'EESL - Ludhiana Junction 6',
    operator: 'EESL',
    lat: 30.8700,
    lng: 75.8373,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs159',
    name: 'Fortum - Rajkot Junction 7',
    operator: 'Fortum',
    lat: 22.2939,
    lng: 70.8022,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'busy'
  },
  {
    id: 'cs160',
    name: 'ChargeZone - Bhavnagar Junction 8',
    operator: 'ChargeZone',
    lat: 21.7745,
    lng: 72.1719,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs161',
    name: 'Tata Power - Jamnagar Junction 1',
    operator: 'Tata Power',
    lat: 22.5007,
    lng: 70.0977,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs162',
    name: 'EESL - Surat Junction 2',
    operator: 'EESL',
    lat: 21.2202,
    lng: 72.8911,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs163',
    name: 'Fortum - Vadodara Junction 3',
    operator: 'Fortum',
    lat: 22.2572,
    lng: 73.1212,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs164',
    name: 'ChargeZone - Panaji Junction 4',
    operator: 'ChargeZone',
    lat: 15.4609,
    lng: 73.7878,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs165',
    name: 'Tata Power - Mangalore Junction 5',
    operator: 'Tata Power',
    lat: 12.9041,
    lng: 74.8360,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs166',
    name: 'EESL - Kozhikode Junction 6',
    operator: 'EESL',
    lat: 11.2688,
    lng: 75.7804,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs167',
    name: 'Fortum - Kollam Junction 7',
    operator: 'Fortum',
    lat: 8.9232,
    lng: 76.6341,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs168',
    name: 'ChargeZone - Kochi Junction 8',
    operator: 'ChargeZone',
    lat: 9.9812,
    lng: 76.3073,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs169',
    name: 'Tata Power - Trivandrum Junction 1',
    operator: 'Tata Power',
    lat: 8.4741,
    lng: 76.9966,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.5,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs170',
    name: 'EESL - Pondicherry Junction 2',
    operator: 'EESL',
    lat: 11.9116,
    lng: 79.7483,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 2,
    total: 3,
    pricePerKwh: 15,
    rating: 3.8,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs171',
    name: 'Fortum - Guntur Junction 3',
    operator: 'Fortum',
    lat: 16.2967,
    lng: 80.3965,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 4,
    total: 4,
    pricePerKwh: 16,
    rating: 4.0,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs172',
    name: 'ChargeZone - Kurnool Junction 4',
    operator: 'ChargeZone',
    lat: 15.8381,
    lng: 78.0173,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 1,
    total: 2,
    pricePerKwh: 17,
    rating: 4.1,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs173',
    name: 'Tata Power - Coorg Junction 5',
    operator: 'Tata Power',
    lat: 12.4560,
    lng: 75.7382,
    chargerTypes: ['DC Fast', 'AC Slow'],
    maxPower: 50,
    available: 3,
    total: 3,
    pricePerKwh: 18,
    rating: 4.2,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs174',
    name: 'EESL - Mysuru Junction 6',
    operator: 'EESL',
    lat: 12.3458,
    lng: 76.6594,
    chargerTypes: ['DC Fast', 'CCS2', 'CHAdeMO'],
    maxPower: 60,
    available: 3,
    total: 4,
    pricePerKwh: 19,
    rating: 4.3,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  },
  {
    id: 'cs175',
    name: 'Fortum - Madurai Junction 7',
    operator: 'Fortum',
    lat: 9.8752,
    lng: 78.1598,
    chargerTypes: ['DC Fast', 'CCS2'],
    maxPower: 40,
    available: 2,
    total: 2,
    pricePerKwh: 14,
    rating: 4.4,
    amenities: ['Restroom', 'Cafe', 'WiFi'],
    status: 'available'
  }
];

export interface RouteStop {
  id: string;
  type: 'start' | 'charging' | 'destination';
  name: string;
  lat: number;
  lng: number;
  arrivalBattery: number;
  departureBattery: number;
  chargeTime?: number; // minutes
  station?: ChargingStation;
  distance: number; // km from previous stop
  eta: string;
}

export interface RouteOption {
  id: string;
  type: 'fastest' | 'cheapest' | 'safest' | 'greenest';
  name: string;
  description: string;
  totalDistance: number;
  totalTime: number; // minutes
  totalCost: number; // INR
  chargingStops: number;
  co2Saved: number; // kg
  fuelSaved: number; // liters
  greenScore: number; // 0-100
  stops: RouteStop[];
  riskLevel: 'safe' | 'caution' | 'danger';
}

export interface Location {
  name: string;
  lat: number;
  lng: number;
}

export const indianCities: Location[] = [
  { name: 'New Delhi', lat: 28.6139, lng: 77.2090 },
  { name: 'Mumbai', lat: 19.0760, lng: 72.8777 },
  { name: 'Bangalore', lat: 12.9716, lng: 77.5946 },
  { name: 'Chennai', lat: 13.0827, lng: 80.2707 },
  { name: 'Kolkata', lat: 22.5726, lng: 88.3639 },
  { name: 'Hyderabad', lat: 17.3850, lng: 78.4867 },
  { name: 'Pune', lat: 18.5204, lng: 73.8567 },
  { name: 'Ahmedabad', lat: 23.0225, lng: 72.5714 },
  { name: 'Jaipur', lat: 26.9124, lng: 75.7873 },
  { name: 'Lucknow', lat: 26.8467, lng: 80.9462 },
  { name: 'Agra', lat: 27.1767, lng: 78.0081 },
  { name: 'Bhopal', lat: 23.2599, lng: 77.4126 },
  { name: 'Chandigarh', lat: 30.7333, lng: 76.7794 },
  { name: 'Goa', lat: 15.2993, lng: 74.1240 },
  { name: 'Udaipur', lat: 24.5854, lng: 73.7125 },
];
